[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
staking = "EsH6cNX6mxNqZcm5bmXAUPfqdfffqDm87Ec8CPp4GAjq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/apollo/pl-staking/staking/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
